# Generated by Django 4.1.7 on 2023-03-05 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_is_mentor'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='audience',
            field=models.CharField(blank=True, choices=[('small', 'у меня маленькая аудитория'), ('enough', 'у меня достаточная аудитория'), ('no', 'в настоящий момент нет')], max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='experience',
            field=models.CharField(blank=True, choices=[('personal', 'лично, частным образом'), ('professional', 'лично, профессионально'), ('online', 'онлайн'), ('other', 'другое')], max_length=20),
        ),
        migrations.DeleteModel(
            name='Mentor',
        ),
    ]
