# Generated by Django 4.1.7 on 2023-03-10 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_mentor',
            field=models.BooleanField(),
        ),
    ]
